import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
	subsets: ["latin"],
});

import "@/styles/globals.css";

export const metadata: Metadata = {
	title: "Example Landing Page",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={inter.className}>
			<body className="bg-gray-100">
				<main className="mx-auto max-w-3xl px-4 py-8">{children}</main>
			</body>
		</html>
	);
}
