import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({
	subsets: ["latin"],
});

import "@/styles/globals.css";

export const metadata: Metadata = {
	title: "Example Landing Page",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={inter.className}>
			<body className="flex min-h-screen flex-col bg-gray-100">
				<Header />
				<main className="w-full grow p-8 md:px-20 lg:px-32">
					<div className="mx-auto max-w-7xl">{children}</div>
				</main>
				<Footer />
			</body>
		</html>
	);
}
